#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database
- name: Run database
  community.docker.docker_container:
    name: "{{ db_container }}"
    image: "eucko/tp-devops-database"
    pull: true
    restart_policy: always
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ db_name }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
    volumes:
      - db-data:/var/lib/postgresql/data