#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/app
- name: Run backend API
  community.docker.docker_container:
    name: "{{ api_container }}"
    image: "eucko/tp-devops-simple-api"
    pull: true
    restart_policy: always
    networks:
      - name: app-network
    env:
      DATABASE_HOST: "{{ db_container }}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ db_container }}:5432/{{ db_name }}"
      SPRING_DATASOURCE_USERNAME: "{{ db_user }}"
      SPRING_DATASOURCE_PASSWORD: "{{ db_password }}"
