name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: pip install ansible

      - name: SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa


      - name: Deploiement Ansible
        working-directory: ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_PRIVATE_KEY_FILE: "/home/runner/.ssh/id_rsa"
        run: ansible-playbook -i inventories/setup.yml playbook.yml -u admin -b