name: Deploy

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name : checkout repositories 
          uses: actions/checkout@v4

                
        - name: Install Ansible
          run: pip install ansible

                
        - name: SSH key
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          run: | 
          echo "$SSH_PRIVATE_KEY" > $HOME/deploy_key chmod 600 $HOME/deploy_key

                
        - name: Deploiement Ansible
          working-directory: ansible
          env:
              ANSIBLE_HOST_KEY_CHECKING: "False"
              DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
              run: ansible-playbook -i inventories/setup.yml playbook.yml -e ansible_ssh_private_key_file=$HOME/deploy_key -e dockerhub_token=$DOCKERHUB_TOKEN
